Repository clamp-orchestrator/clamp-core, pull requests merged in 2020-10, with the labels that each got.

#39 Refactoring workflow creation code to remove nested step update
  models/workflow.go
Labels: code quality

#49 Removed unused variable in env.go
  config/env.go
Labels: code quality

#51 Adding License Badge to the Readme with link redirecting to the LICENSE
  README.md
Labels: documentation

#54 Adding integration with the code climate service
  .circleci/config.yml
  README.md
Labels: code quality, documentation

#58 Run integration test in ci server
  .circleci/config.yml
  main.go
  models/initialization.go
  models/initialization_test.go
Labels: cicd, hacktoberfest, hacktoberfest-accepted

#57 Fetch workflows (GET api)
  .circleci/config.yml
  go.sum
  handlers/workflow_handler.go
  handlers/workflow_handler_test.go
  models/sort_fields.go
  models/sort_fields_test.go
  repository/db.go
  repository/postgres.go
  services/abstract_test.go
  services/service_request_service.go
  services/workflow_service.go
  services/workflow_service_test.go
Labels: enhancement

#72 #68 | Kafka or Rabbitmq to be optional to use Clamp
  .circleci/config.yml
  config/env.go
  main.go
Labels: backend, enhancement, hacktoberfest
